version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "GitHub Actions":
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "Container Images":
        patterns:
          - "*"
  - package-ecosystem: "helm"
    directory: "/"
    schedule:
      interval: "daily"
