version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      "GitHub Actions":
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "**"
      - "/components/apps/**"
    schedule:
      interval: "daily"
    groups:
      "Container Images":
        patterns:
          - "*"
  - package-ecosystem: "helm"
    directories:
      - "/"
      - "**"
    schedule:
      interval: "daily"
