global:
  monitoring:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack

master:
  data:
    storageClass: longhorn

volume:
  dataDirs:
    - name: s3
      type: "persistentVolumeClaim"
      size: "10Gi"
      storageClass: "longhorn"
      maxVolumes: 1

filer:
  enabled: true
  enablePVC: true
  storage: 10Gi
  storageClass: longhorn
  data:
    type: "persistentVolumeClaim"
    size: "10Gi"
    storageClass: "longhorn"
  s3:
    enabled: true
    domainName: "redcomet.ca"
    enableAuth: true
    existingConfigSecret: s3-creds
