auth:
  adminUser: keycloak
  existingSecret: keycloak-admin
  passwordSecretKey: password
global:
  defaultStorageClass: longhorn
  storageClass: longhorn
metrics:
  enabled: true
  prometheusRule:
    enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
extraEnvVars:
  - name: KC_HOSTNAME
    value: keycloak.redcomet.ca
  - name: KC_PROXY
    value: edge
  - name: KC_PRODUCTION
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_PROXY_HEADERS
    value: xforwarded
postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: keycloak
    database: bitnami_keycloak
