apiVersion: v1
data:
  additional-scrape-configs.yaml: LSBqb2JfbmFtZTogInVuYm91bmQiCiAgc3RhdGljX2NvbmZpZ3M6CiAgICAtIHRhcmdldHM6IFsiMTcyLjE2LjAuMTo5MTY3Il0KLSBqb2JfbmFtZTogIm1pa3JvdGlrIgogIHN0YXRpY19jb25maWdzOgogICAgLSB0YXJnZXRzOiBbIm1rdHhwLWV4cG9ydGVyOjQ5MDkwIl0KLSBqb2JfbmFtZTogImZlbnJpciIKICBzdGF0aWNfY29uZmlnczoKICAgIC0gdGFyZ2V0czogWyJmZW5yaXIucmVkY29tZXQuY2E6OTEwMCJdCi0gam9iX25hbWU6ICJ6ZnMiCiAgc3RhdGljX2NvbmZpZ3M6CiAgICAtIHRhcmdldHM6IFsiZmVucmlyLnJlZGNvbWV0LmNhOjkxMzQiXQo=
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
