apiVersion: v1
data:
  additional-scrape-configs.yaml: LSBqb2JfbmFtZTogInVuYm91bmQiCiAgc3RhdGljX2NvbmZpZ3M6CiAgICAtIHRhcmdldHM6IFsiMTcyLjE2LjAuMTo5MTY3Il0KLSBqb2JfbmFtZTogIm1pa3JvdGlrIgogIHN0YXRpY19jb25maWdzOgogICAgLSB0YXJnZXRzOiBbIm1rdHhwLWV4cG9ydGVyOjQ5MDkwIl0KLSBqb2JfbmFtZTogImZlbnJpciIKICBzdGF0aWNfY29uZmlnczoKICAgIC0gdGFyZ2V0czogWyJmZW5yaXIucmVkY29tZXQuY2E6OTEwMCJdCi0gam9iX25hbWU6ICJmZW5yaXItc21hcnRjdGwiCiAgc3RhdGljX2NvbmZpZ3M6CiAgICAtIHRhcmdldHM6IFsiZmVucmlyLnJlZGNvbWV0LmNhOjk2MzMiXQotIGpvYl9uYW1lOiAiemZzIgogIHN0YXRpY19jb25maWdzOgogICAgLSB0YXJnZXRzOiBbImZlbnJpci5yZWRjb21ldC5jYTo5MTM0Il0K
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
