persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
  defaultReplicaCount: "1"
defaultBackupStore:
  backupTargetCredentialSecret: rustfs-secret
  backupTarget: s3://k0s-backup@ca-west-1/longhorn
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
