apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustfs-console
  namespace: rustfs
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`rustfs.redcomet.ca`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: rustfs-svc
          port: 9001
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rustfs-s3
  namespace: rustfs
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`s3.redcomet.ca`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: rustfs-svc
          port: 9000
