replicaCount: 1

secret:
  existingSecret: rustfs-secret

config:
  volumes: "/data/rustfs0"
  region: "ca-west-1"

mode:
  standalone:
    enabled: true
  distributed:
    enabled: false

storageclass:
  name: fenrir-iscsi
  dataStorageSize: 100Gi
  logStorageSize: 1Gi

ingress:
  enabled: false

hosts:
  - host: s3.redcomet.ca
    paths:
      - path: /
        pathType: Prefix
